# Generated by Django 5.0.1 on 2024-01-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_userprofile_current_balance_userprofile_member_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
