# Generated by Django 5.0.1 on 2024-01-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_captcharecord_captchaplanrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
