# Generated by Django 5.0.1 on 2024-02-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_withdrawtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='refferal_id',
            field=models.CharField(default='reff_id', max_length=50),
        ),
    ]
