# Generated by Django 5.0.1 on 2024-02-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_paymenttransaction_refferal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='transactionId',
            field=models.CharField(default='transctn_id', max_length=50),
        ),
    ]
