# Generated by Django 5.0.1 on 2024-02-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_paymenttransaction_transactionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='referral_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
