# Generated by Django 5.0.1 on 2024-02-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_plan_referral_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_screenshot',
            field=models.ImageField(blank=True, default='default_payment_screenshot.jpg', null=True, upload_to='images/'),
        ),
    ]
