# Generated by Django 5.0.1 on 2024-02-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_paymenttransaction_payment_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_screenshot',
            field=models.ImageField(blank=True, default='default_payment_screenshot.jpg', null=True, upload_to='media/images/'),
        ),
    ]
