# Generated by Django 5.0.1 on 2024-02-08 16:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_paymenttransaction_payment_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='captchaplanrecord',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='plan',
            name='duration',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_screenshot',
            field=models.ImageField(blank=True, default='default_payment_screenshot.jpg', null=True, upload_to='screenshots/images/'),
        ),
    ]
