# Generated by Django 5.0.1 on 2024-02-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_captchaplanrecord_start_date_plan_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='withdraw_limit',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
