# Generated by Django 5.0.1 on 2024-02-09 00:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_plan_withdraw_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchaplanrecord',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
