# Generated by Django 5.0.1 on 2024-01-26 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_plan_amount'),
        ('users', '0002_user_balance_rps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='balance_rps',
            new_name='current_balance',
        ),
        migrations.AddField(
            model_name='user',
            name='current_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.plan', verbose_name=''),
        ),
    ]
