# Generated by Django 5.0.1 on 2024-01-26 05:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_balance_rps_user_current_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default=1010101010, max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_10_digits', message='Must be exactly 10 digits.', regex='^\\d{10}$')]),
            preserve_default=False,
        ),
    ]
