# Generated by Django 5.0.1 on 2024-01-26 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_10_digits', message='Must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
