# Generated by Django 5.0.1 on 2024-02-06 03:08

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_referral_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_id',
            field=models.CharField(default=users.models.generate_unique_id, editable=False, max_length=7),
        ),
    ]
