# Generated by Django 5.0.1 on 2024-02-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_referral_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='times_reffered',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
